### ISSUE TITLE
Resourcepack path typo?

### ISSUE THREAD

**Issue by barraIhsan** [JoshuaVandaele/ICU#2]
Is supposed to be `textures/block` not `textures/blocks` (in vanilla). Yes, it will work but it kinda annoying because you need to add new folder named `blocks` in textures folder just for the barrier texture

(Yes i know it can be changed in models but it should be default)

**Comment by JoshuaVandaele** [comment]
Fixed with commit 1b8bd4523ddad03e8082521a17208c2731db271e
