### ISSUE TITLE
[FEATURE] Toggle barrier texture and particle

### ISSUE THREAD

**Issue by barraIhsan** [JoshuaVandaele/ICU#3]
So im pretty sure anyone doesnt want to see the barrier 24/7 so maybe add a keybind / command / gui to toggle the barrier texture and also to toggle particle

Because who want see the barrier particle when you have the textures? (yes i know, I doesn't put the resourcepack yet, I just show the barrier particle)
![image](https://user-images.githubusercontent.com/57800056/111925362-2fd6a880-8adb-11eb-8688-27eb7314b2be.png)

**Comment by JoshuaVandaele** [comment]
I will not personally be adding this, but if someone wants to implement this PRs are open.
